# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="Django<1.9"
  - DJANGO="Django<1.10"
  - DJANGO="Django<1.11"
  - DJANGO="Django<1.12"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.11"
    - python: "3.3"
      env: DJANGO="Django<1.12"

before_install:
  - pip install codecov
  - pip install flake8
  - flake8 .

install:
  - pip install -r requirements/requirements_test.txt
  - pip install --upgrade "$DJANGO"

script: coverage run --source mozilla_django_oidc runtests.py

after_success:
  - codecov
